### ISSUE TITLE
Same as NorAdrenaline

### ISSUE THREAD

**Issue by hasanalizxc** [danielkrupinski/Caesar#2]
Dear Daniel,

Hope you are fine. I tested Caesar but it didn't work for me. I used Extreme Injector 3.73 and standard method but when i try yo inject i am taking "null return exception". Then i tested with manual map method, in this time game crashed. Can you help me?

Thanks.

**Comment by danielkrupinski** [comment]
Dear hasanalizxc,

The cheat is designed to work with latest Steam version of **CS 1.6**. It won't work on any non-steam or cracked version of the game.

Anyway, try using another injector like Xenos.

Best regards,
Daniel

**Comment by hasanalizxc** [comment]
Dear daniel,

Thank you so much for reply. I will test it with another injectors.

**Comment by hasanalizxc** [comment]
Dear Daniel,

Firstable this cheat **works** steam and non-steam because this cheat's name is **NorAdrenaline** as you know. Which **modification** did you make to this cheat and it didn't work on non-steam version of CS 1.6 i wonder.

Secondary i tried with Xenos, result is **same**.

**Comment by danielkrupinski** [comment]
Dear hasanalizxc,

As stated in [README](README.md) the cheat works **only** with official CS 1.6.

Please **don't** expect any support for non-steam games as there will be none.

Best regards,
Daniel

**Comment by hasanalizxc** [comment]
Dear Daniel,

I **don't** expect any support for non-steam games. I just wondered and asked what is the **difference** between NorAdrenaline? Did you make any **upgrade** or just **changed** names of the files? If you answer these, i appreciate you.

Kind Regards,
hasanalizxc

**Comment by danielkrupinski** [comment]
Dear hasanalizxc,

So far cheat has brand **new JSON-based** config system, slightly changed **menu layout** and replaced C-style constructs with **modern C++** ones.

Best regards,
Daniel

**Comment by hasanalizxc** [comment]
Dear Daniel,

I envy now but i don't have a Steam account and can't test it.

Thank you so much for your interest.

Have a happy life.

Kind Regards,
hasanalizxc

**Comment by imgladnotu** [comment]
Hi, ive been testing Caesar with various and different versions of counter-strike, however i have not tested it with either condition zero or condition zero deleted scenes, and i am disappointed to say that apparently it it crashes when after picking a faction (either ct or t) and one or two letters disappear from the first option, if you're wondering what injector that i was using, i was using: Winject,sinject,DCinjector(uc priv forums dll inj),Xenos 2.3.2.0 and Extreme Injector 3.7.2.0, tried various options throughout the different injectors and to no avail.
![2019-01-05_15-40-16](https://user-images.githubusercontent.com/46180501/51036652-ba144f80-15e8-11e9-8874-1e5ea7130027.png)
