### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by mentoryLe** [danielkrupinski/Caesar#3]
When I join any team (except SPECTATOR) it crashes my cs, can you help me? 
Thank you in advance!

**Comment by danielkrupinski** [comment]
First off all make sure you are using unmodded Steam version of CS 1.6.
Then try joining other servers or create local game and check if it crashes.

**Comment by danielkrupinski** [comment]
I checked this out and it seemed to be caused by weapon name drawing option.
It's now fixed so try the cheat once again.

**Comment by mentoryLe** [comment]
Hey, i've tested again and its still not working, can you take a look on this video?
https://youtu.be/T3IrvnFriuk

Thank you so much, sry =)

**Comment by danielkrupinski** [comment]
Bots aren't available in Steam CS 1.6. Are you surely using unmodified game? [This article](https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335) may help you.

I have tried to reproduce this issue but cheat works fine for me all the time.

**Comment by mentoryLe** [comment]
Can you send me the compiled file? I'll test on a vac banned account, if it doesnt works its bcuz my pc is fucked.
Thanks

**Comment by danielkrupinski** [comment]
[Here you are](https://github.com/danielkrupinski/Caesar/releases/download/v1.0/Caesar.dll).

**Comment by mentoryLe** [comment]
yup, still crashing.. i'll install a fresh copy of windows here. anyway thank you so much for your time. Sorry =D, have a good day!
